<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<!DOCTYPE stats [
<!ELEMENT stats (ship)*>
<!ELEMENT ship (name, race, class, target1, target2, target3, type, initiative, guns, armor, damage, empres, metal, crystal, eonium, armorcost, damagecost)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT race (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT target1 (#PCDATA)>
<!ELEMENT target2 (#PCDATA)>
<!ELEMENT target3 (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT initiative (#PCDATA)>
<!ELEMENT guns (#PCDATA)>
<!ELEMENT armor (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT empres (#PCDATA)>
<!ELEMENT metal (#PCDATA)>
<!ELEMENT crystal (#PCDATA)>
<!ELEMENT eonium (#PCDATA)>
<!ELEMENT armorcost (#PCDATA)>
<!ELEMENT damagecost (#PCDATA)>
]>
<stats>
	<ship>
		<name>Harpy</name>
		<race>Terran</race>
		<class>Fighter</class>
		<target1>Corvette</target1>
		<target2>Fighter</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>6</initiative>
		<guns>1</guns>
		<armor>6</armor>
		<damage>3</damage>
		<empres>11</empres>
		<metal>51</metal>
		<crystal>41</crystal>
		<eonium>41</eonium>
		<armorcost>451</armorcost>
		<damagecost>225</damagecost>
	</ship>
	<ship>
		<name>Phoenix</name>
		<race>Terran</race>
		<class>Corvette</class>
		<target1>Fighter</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>7</initiative>
		<guns>1</guns>
		<armor>12</armor>
		<damage>11</damage>
		<empres>12</empres>
		<metal>107</metal>
		<crystal>95</crystal>
		<eonium>95</eonium>
		<armorcost>404</armorcost>
		<damagecost>370</damagecost>
	</ship>
	<ship>
		<name>Sylph</name>
		<race>Terran</race>
		<class>Corvette</class>
		<target1>Frigate</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>5</initiative>
		<guns>1</guns>
		<armor>12</armor>
		<damage>8</damage>
		<empres>12</empres>
		<metal>106</metal>
		<crystal>96</crystal>
		<eonium>96</eonium>
		<armorcost>402</armorcost>
		<damagecost>268</damagecost>
	</ship>
	<ship>
		<name>Pegasus</name>
		<race>Terran</race>
		<class>Frigate</class>
		<target1>Destroyer</target1>
		<target2>Corvette</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>20</initiative>
		<guns>1</guns>
		<armor>43</armor>
		<damage>14</damage>
		<empres>49</empres>
		<metal>295</metal>
		<crystal>260</crystal>
		<eonium>260</eonium>
		<armorcost>527</armorcost>
		<damagecost>171</damagecost>
	</ship>
	<ship>
		<name>Centaur</name>
		<race>Terran</race>
		<class>Destroyer</class>
		<target1>Cruiser</target1>
		<target2>Battleship</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>15</initiative>
		<guns>1</guns>
		<armor>47</armor>
		<damage>38</damage>
		<empres>67</empres>
		<metal>450</metal>
		<crystal>415</crystal>
		<eonium>415</eonium>
		<armorcost>367</armorcost>
		<damagecost>296</damagecost>
	</ship>
	<ship>
		<name>Syren</name>
		<race>Terran</race>
		<class>Cruiser</class>
		<target1>Battleship</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>7</initiative>
		<guns>1</guns>
		<armor>120</armor>
		<damage>97</damage>
		<empres>78</empres>
		<metal>1055</metal>
		<crystal>995</crystal>
		<eonium>995</eonium>
		<armorcost>394</armorcost>
		<damagecost>318</damagecost>
	</ship>
	<ship>
		<name>Hydra</name>
		<race>Terran</race>
		<class>Cruiser</class>
		<target1>Destroyer</target1>
		<target2>Frigate</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>14</initiative>
		<guns>1</guns>
		<armor>125</armor>
		<damage>100</damage>
		<empres>79</empres>
		<metal>1105</metal>
		<crystal>1020</crystal>
		<eonium>1020</eonium>
		<armorcost>397</armorcost>
		<damagecost>317</damagecost>
	</ship>
	<ship>
		<name>Dragon</name>
		<race>Terran</race>
		<class>Battleship</class>
		<target1>Cruiser</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>8</initiative>
		<guns>1</guns>
		<armor>183</armor>
		<damage>105</damage>
		<empres>95</empres>
		<metal>1680</metal>
		<crystal>1470</crystal>
		<eonium>1470</eonium>
		<armorcost>396</armorcost>
		<damagecost>227</damagecost>
	</ship>
	<ship>
		<name>Valkyrie</name>
		<race>Terran</race>
		<class>Corvette</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>13</armor>
		<damage>10</damage>
		<empres>13</empres>
		<metal>100</metal>
		<crystal>100</crystal>
		<eonium>100</eonium>
		<armorcost>433</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Cerberus</name>
		<race>Terran</race>
		<class>Cruiser</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>141</armor>
		<damage>117</damage>
		<empres>81</empres>
		<metal>1175</metal>
		<crystal>1175</crystal>
		<eonium>1175</eonium>
		<armorcost>400</armorcost>
		<damagecost>331</damagecost>
	</ship>
	<ship>
		<name>Leviathan</name>
		<race>Terran</race>
		<class>Battleship</class>
		<target1>Structure</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Structure</type>
		<initiative>40</initiative>
		<guns>1</guns>
		<armor>120</armor>
		<damage>55</damage>
		<empres>89</empres>
		<metal>1500</metal>
		<crystal>1500</crystal>
		<eonium>1500</eonium>
		<armorcost>266</armorcost>
		<damagecost>122</damagecost>
	</ship>
	<ship>
		<name>Spider</name>
		<race>Cathaar</race>
		<class>Fighter</class>
		<target1>Corvette</target1>
		<target2>Fighter</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>8</initiative>
		<guns>1</guns>
		<armor>6</armor>
		<damage>3</damage>
		<empres>44</empres>
		<metal>58</metal>
		<crystal>45</crystal>
		<eonium>45</eonium>
		<armorcost>405</armorcost>
		<damagecost>202</damagecost>
	</ship>
	<ship>
		<name>Beetle</name>
		<race>Cathaar</race>
		<class>Corvette</class>
		<target1>Fighter</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>1</initiative>
		<guns>4</guns>
		<armor>18</armor>
		<damage>-</damage>
		<empres>27</empres>
		<metal>106</metal>
		<crystal>126</crystal>
		<eonium>106</eonium>
		<armorcost>532</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Viper</name>
		<race>Cathaar</race>
		<class>Frigate</class>
		<target1>Destroyer</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>3</initiative>
		<guns>3</guns>
		<armor>31</armor>
		<damage>-</damage>
		<empres>51</empres>
		<metal>275</metal>
		<crystal>299</crystal>
		<eonium>275</eonium>
		<armorcost>365</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Scarab</name>
		<race>Cathaar</race>
		<class>Destroyer</class>
		<target1>Frigate</target1>
		<target2>Cruiser</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>3</initiative>
		<guns>5</guns>
		<armor>63</armor>
		<damage>-</damage>
		<empres>70</empres>
		<metal>462</metal>
		<crystal>502</crystal>
		<eonium>462</eonium>
		<armorcost>441</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Widow</name>
		<race>Cathaar</race>
		<class>Destroyer</class>
		<target1>Battleship</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>22</initiative>
		<guns>1</guns>
		<armor>63</armor>
		<damage>35</damage>
		<empres>80</empres>
		<metal>457</metal>
		<crystal>457</crystal>
		<eonium>520</eonium>
		<armorcost>439</armorcost>
		<damagecost>244</damagecost>
	</ship>
	<ship>
		<name>Mantis</name>
		<race>Cathaar</race>
		<class>Cruiser</class>
		<target1>Battleship</target1>
		<target2>Frigate</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>3</initiative>
		<guns>19</guns>
		<armor>130</armor>
		<damage>-</damage>
		<empres>79</empres>
		<metal>1052</metal>
		<crystal>1140</crystal>
		<eonium>1052</eonium>
		<armorcost>400</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Roach</name>
		<race>Cathaar</race>
		<class>Battleship</class>
		<target1>Destroyer</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>2</initiative>
		<guns>15</guns>
		<armor>170</armor>
		<damage>-</damage>
		<empres>94</empres>
		<metal>1365</metal>
		<crystal>1550</crystal>
		<eonium>1365</eonium>
		<armorcost>397</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Tarantula</name>
		<race>Cathaar</race>
		<class>Battleship</class>
		<target1>Cruiser</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>1</initiative>
		<guns>9</guns>
		<armor>170</armor>
		<damage>-</damage>
		<empres>94</empres>
		<metal>1390</metal>
		<crystal>1522</crystal>
		<eonium>1390</eonium>
		<armorcost>395</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Wasp</name>
		<race>Cathaar</race>
		<class>Destroyer</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>66</armor>
		<damage>49</damage>
		<empres>71</empres>
		<metal>493</metal>
		<crystal>493</crystal>
		<eonium>493</eonium>
		<armorcost>446</armorcost>
		<damagecost>331</damagecost>
	</ship>
	<ship>
		<name>Hornet</name>
		<race>Cathaar</race>
		<class>Battleship</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>174</armor>
		<damage>145</damage>
		<empres>94</empres>
		<metal>1450</metal>
		<crystal>1450</crystal>
		<eonium>1450</eonium>
		<armorcost>400</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Termite</name>
		<race>Cathaar</race>
		<class>Cruiser</class>
		<target1>Structure</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Structure</type>
		<initiative>40</initiative>
		<guns>1</guns>
		<armor>107</armor>
		<damage>50</damage>
		<empres>66</empres>
		<metal>1400</metal>
		<crystal>1400</crystal>
		<eonium>1400</eonium>
		<armorcost>254</armorcost>
		<damagecost>119</damagecost>
	</ship>
	<ship>
		<name>Phantom</name>
		<race>Xandathrii</race>
		<class>Fighter</class>
		<target1>Corvette</target1>
		<target2>Fighter</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>4</initiative>
		<guns>1</guns>
		<armor>5</armor>
		<damage>4</damage>
		<empres>23</empres>
		<metal>55</metal>
		<crystal>55</crystal>
		<eonium>55</eonium>
		<armorcost>303</armorcost>
		<damagecost>242</damagecost>
	</ship>
	<ship>
		<name>Banshee</name>
		<race>Xandathrii</race>
		<class>Corvette</class>
		<target1>Fighter</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>4</initiative>
		<guns>1</guns>
		<armor>10</armor>
		<damage>8</damage>
		<empres>13</empres>
		<metal>110</metal>
		<crystal>110</crystal>
		<eonium>110</eonium>
		<armorcost>303</armorcost>
		<damagecost>242</damagecost>
	</ship>
	<ship>
		<name>Bomber</name>
		<race>Xandathrii</race>
		<class>Frigate</class>
		<target1>Corvette</target1>
		<target2>Cruiser</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>15</initiative>
		<guns>1</guns>
		<armor>25</armor>
		<damage>24</damage>
		<empres>44</empres>
		<metal>263</metal>
		<crystal>263</crystal>
		<eonium>263</eonium>
		<armorcost>316</armorcost>
		<damagecost>304</damagecost>
	</ship>
	<ship>
		<name>Ghost</name>
		<race>Xandathrii</race>
		<class>Frigate</class>
		<target1>Destroyer</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>5</initiative>
		<guns>1</guns>
		<armor>27</armor>
		<damage>36</damage>
		<empres>48</empres>
		<metal>283</metal>
		<crystal>283</crystal>
		<eonium>283</eonium>
		<armorcost>318</armorcost>
		<damagecost>424</damagecost>
	</ship>
	<ship>
		<name>Fireblade</name>
		<race>Xandathrii</race>
		<class>Destroyer</class>
		<target1>Cruiser</target1>
		<target2>Battleship</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>16</initiative>
		<guns>1</guns>
		<armor>47</armor>
		<damage>45</damage>
		<empres>67</empres>
		<metal>450</metal>
		<crystal>450</crystal>
		<eonium>450</eonium>
		<armorcost>348</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Spectre</name>
		<race>Xandathrii</race>
		<class>Cruiser</class>
		<target1>Battleship</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>9</initiative>
		<guns>1</guns>
		<armor>103</armor>
		<damage>93</damage>
		<empres>75</empres>
		<metal>942</metal>
		<crystal>942</crystal>
		<eonium>942</eonium>
		<armorcost>364</armorcost>
		<damagecost>329</damagecost>
	</ship>
	<ship>
		<name>Wraith</name>
		<race>Xandathrii</race>
		<class>Cruiser</class>
		<target1>Destroyer</target1>
		<target2>Frigate</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>11</initiative>
		<guns>1</guns>
		<armor>108</armor>
		<damage>105</damage>
		<empres>76</empres>
		<metal>998</metal>
		<crystal>998</crystal>
		<eonium>998</eonium>
		<armorcost>360</armorcost>
		<damagecost>350</damagecost>
	</ship>
	<ship>
		<name>Mimic</name>
		<race>Xandathrii</race>
		<class>Frigate</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>29</armor>
		<damage>29</damage>
		<empres>50</empres>
		<metal>292</metal>
		<crystal>292</crystal>
		<eonium>292</eonium>
		<armorcost>331</armorcost>
		<damagecost>331</damagecost>
	</ship>
	<ship>
		<name>Vampire</name>
		<race>Xandathrii</race>
		<class>Cruiser</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>103</armor>
		<damage>94</damage>
		<empres>75</empres>
		<metal>940</metal>
		<crystal>940</crystal>
		<eonium>940</eonium>
		<armorcost>365</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Haunt</name>
		<race>Xandathrii</race>
		<class>Battleship</class>
		<target1>Structure</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Structure</type>
		<initiative>40</initiative>
		<guns>1</guns>
		<armor>100</armor>
		<damage>55</damage>
		<empres>87</empres>
		<metal>1400</metal>
		<crystal>1400</crystal>
		<eonium>1400</eonium>
		<armorcost>238</armorcost>
		<damagecost>130</damagecost>
	</ship>
	<ship>
		<name>Cutlass</name>
		<race>Zikonian</race>
		<class>Fighter</class>
		<target1>Corvette</target1>
		<target2>Fighter</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>24</initiative>
		<guns>1</guns>
		<armor>7</armor>
		<damage>4</damage>
		<empres>21</empres>
		<metal>49</metal>
		<crystal>49</crystal>
		<eonium>62</eonium>
		<armorcost>437</armorcost>
		<damagecost>250</damagecost>
	</ship>
	<ship>
		<name>Corsair</name>
		<race>Zikonian</race>
		<class>Corvette</class>
		<target1>Frigate</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>19</initiative>
		<guns>1</guns>
		<armor>10</armor>
		<damage>8</damage>
		<empres>16</empres>
		<metal>99</metal>
		<crystal>99</crystal>
		<eonium>114</eonium>
		<armorcost>320</armorcost>
		<damagecost>256</damagecost>
	</ship>
	<ship>
		<name>Ravager</name>
		<race>Zikonian</race>
		<class>Corvette</class>
		<target1>Fighter</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>5</initiative>
		<guns>1</guns>
		<armor>10</armor>
		<damage>12</damage>
		<empres>14</empres>
		<metal>110</metal>
		<crystal>98</crystal>
		<eonium>98</eonium>
		<armorcost>326</armorcost>
		<damagecost>392</damagecost>
	</ship>
	<ship>
		<name>Clipper</name>
		<race>Zikonian</race>
		<class>Frigate</class>
		<target1>Destroyer</target1>
		<target2>Cruiser</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>7</initiative>
		<guns>1</guns>
		<armor>30</armor>
		<damage>34</damage>
		<empres>44</empres>
		<metal>285</metal>
		<crystal>252</crystal>
		<eonium>252</eonium>
		<armorcost>380</armorcost>
		<damagecost>430</damagecost>
	</ship>
	<ship>
		<name>Thief</name>
		<race>Zikonian</race>
		<class>Frigate</class>
		<target1>Corvette</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>18</initiative>
		<guns>1</guns>
		<armor>28</armor>
		<damage>20</damage>
		<empres>44</empres>
		<metal>258</metal>
		<crystal>258</crystal>
		<eonium>280</eonium>
		<armorcost>351</armorcost>
		<damagecost>251</damagecost>
	</ship>
	<ship>
		<name>Buccaneer</name>
		<race>Zikonian</race>
		<class>Destroyer</class>
		<target1>Frigate</target1>
		<target2>Battleship</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>23</initiative>
		<guns>1</guns>
		<armor>66</armor>
		<damage>44</damage>
		<empres>69</empres>
		<metal>450</metal>
		<crystal>450</crystal>
		<eonium>508</eonium>
		<armorcost>468</armorcost>
		<damagecost>312</damagecost>
	</ship>
	<ship>
		<name>Pirate</name>
		<race>Zikonian</race>
		<class>Cruiser</class>
		<target1>Battleship</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>21</initiative>
		<guns>1</guns>
		<armor>140</armor>
		<damage>70</damage>
		<empres>75</empres>
		<metal>1000</metal>
		<crystal>1000</crystal>
		<eonium>1105</eonium>
		<armorcost>450</armorcost>
		<damagecost>225</damagecost>
	</ship>
	<ship>
		<name>Rogue</name>
		<race>Zikonian</race>
		<class>Battleship</class>
		<target1>Cruiser</target1>
		<target2>Destroyer</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>13</initiative>
		<guns>1</guns>
		<armor>145</armor>
		<damage>130</damage>
		<empres>94</empres>
		<metal>1454</metal>
		<crystal>1360</crystal>
		<eonium>1360</eonium>
		<armorcost>347</armorcost>
		<damagecost>311</damagecost>
	</ship>
	<ship>
		<name>Privateer</name>
		<race>Zikonian</race>
		<class>Corvette</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>10</armor>
		<damage>10</damage>
		<empres>15</empres>
		<metal>100</metal>
		<crystal>100</crystal>
		<eonium>100</eonium>
		<armorcost>333</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Pillager</name>
		<race>Zikonian</race>
		<class>Frigate</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>31</armor>
		<damage>28</damage>
		<empres>47</empres>
		<metal>280</metal>
		<crystal>280</crystal>
		<eonium>280</eonium>
		<armorcost>369</armorcost>
		<damagecost>333</damagecost>
	</ship>
	<ship>
		<name>Galleon</name>
		<race>Zikonian</race>
		<class>Battleship</class>
		<target1>Structure</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Structure</type>
		<initiative>40</initiative>
		<guns>1</guns>
		<armor>115</armor>
		<damage>53</damage>
		<empres>88</empres>
		<metal>1430</metal>
		<crystal>1430</crystal>
		<eonium>1430</eonium>
		<armorcost>268</armorcost>
		<damagecost>123</damagecost>
	</ship>
	<ship>
		<name>Gryphon</name>
		<race>Eitraides</race>
		<class>Fighter</class>
		<target1>Fighter</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>2</initiative>
		<guns>2</guns>
		<armor>6</armor>
		<damage>-</damage>
		<empres>20</empres>
		<metal>53</metal>
		<crystal>63</crystal>
		<eonium>53</eonium>
		<armorcost>355</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Creditor</name>
		<race>Eitraides</race>
		<class>Fighter</class>
		<target1>Corvette</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>1</initiative>
		<guns>1</guns>
		<armor>6</armor>
		<damage>-</damage>
		<empres>20</empres>
		<metal>53</metal>
		<crystal>63</crystal>
		<eonium>53</eonium>
		<armorcost>355</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Dealer</name>
		<race>Eitraides</race>
		<class>Corvette</class>
		<target1>Fighter</target1>
		<target2>Frigate</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>24</initiative>
		<guns>1</guns>
		<armor>12</armor>
		<damage>8</damage>
		<empres>5</empres>
		<metal>95</metal>
		<crystal>95</crystal>
		<eonium>113</eonium>
		<armorcost>396</armorcost>
		<damagecost>264</damagecost>
	</ship>
	<ship>
		<name>Avenger</name>
		<race>Eitraides</race>
		<class>Frigate</class>
		<target1>Corvette</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Steal</type>
		<initiative>24</initiative>
		<guns>1</guns>
		<armor>24</armor>
		<damage>20</damage>
		<empres>42</empres>
		<metal>245</metal>
		<crystal>245</crystal>
		<eonium>278</eonium>
		<armorcost>312</armorcost>
		<damagecost>260</damagecost>
	</ship>
	<ship>
		<name>Judge</name>
		<race>Eitraides</race>
		<class>Destroyer</class>
		<target1>Frigate</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>6</initiative>
		<guns>1</guns>
		<armor>57</armor>
		<damage>56</damage>
		<empres>69</empres>
		<metal>480</metal>
		<crystal>480</crystal>
		<eonium>480</eonium>
		<armorcost>395</armorcost>
		<damagecost>388</damagecost>
	</ship>
	<ship>
		<name>Baliff</name>
		<race>Eitraides</race>
		<class>Destroyer</class>
		<target1>Cruiser</target1>
		<target2>Battleship</target2>
		<target3>-</target3>
		<type>Cloak</type>
		<initiative>12</initiative>
		<guns>1</guns>
		<armor>62</armor>
		<damage>55</damage>
		<empres>72</empres>
		<metal>519</metal>
		<crystal>519</crystal>
		<eonium>519</eonium>
		<armorcost>398</armorcost>
		<damagecost>353</damagecost>
	</ship>
	<ship>
		<name>Illuminator</name>
		<race>Eitraides</race>
		<class>Cruiser</class>
		<target1>Battleship</target1>
		<target2>Destroyer</target2>
		<target3>-</target3>
		<type>Emp</type>
		<initiative>1</initiative>
		<guns>18</guns>
		<armor>122</armor>
		<damage>-</damage>
		<empres>76</empres>
		<metal>975</metal>
		<crystal>1124</crystal>
		<eonium>975</eonium>
		<armorcost>396</armorcost>
		<damagecost>0</damagecost>
	</ship>
	<ship>
		<name>Investor</name>
		<race>Eitraides</race>
		<class>Battleship</class>
		<target1>Cruiser</target1>
		<target2>Destroyer</target2>
		<target3>-</target3>
		<type>Normal</type>
		<initiative>10</initiative>
		<guns>1</guns>
		<armor>148</armor>
		<damage>125</damage>
		<empres>94</empres>
		<metal>1505</metal>
		<crystal>1340</crystal>
		<eonium>1340</eonium>
		<armorcost>353</armorcost>
		<damagecost>298</damagecost>
	</ship>
	<ship>
		<name>Astropod</name>
		<race>Eitraides</race>
		<class>Fighter</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>7</armor>
		<damage>6</damage>
		<empres>26</empres>
		<metal>61</metal>
		<crystal>61</crystal>
		<eonium>61</eonium>
		<armorcost>382</armorcost>
		<damagecost>327</damagecost>
	</ship>
	<ship>
		<name>Merchant</name>
		<race>Eitraides</race>
		<class>Destroyer</class>
		<target1>Roids</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Pod</type>
		<initiative>30</initiative>
		<guns>1</guns>
		<armor>63</armor>
		<damage>52</damage>
		<empres>72</empres>
		<metal>525</metal>
		<crystal>525</crystal>
		<eonium>525</eonium>
		<armorcost>400</armorcost>
		<damagecost>330</damagecost>
	</ship>
	<ship>
		<name>Basilisk</name>
		<race>Eitraides</race>
		<class>Battleship</class>
		<target1>Structure</target1>
		<target2>-</target2>
		<target3>-</target3>
		<type>Structure</type>
		<initiative>40</initiative>
		<guns>1</guns>
		<armor>110</armor>
		<damage>51</damage>
		<empres>88</empres>
		<metal>1500</metal>
		<crystal>1500</crystal>
		<eonium>1500</eonium>
		<armorcost>244</armorcost>
		<damagecost>113</damagecost>
	</ship>
</stats>
